### ISSUE TITLE
Tracking issue for moving to new runner

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#54]
In #46, we introduced a new test runner implementation and conventions but there are many remaining tasks for improving that PR. I am copying the issues listed in https://github.com/bytecodealliance/sightglass/pull/46#issuecomment-742739680 here and will check them off as they are completed:

 - [ ] move and rename `webui/sg-history` to `crates/result-server`
 - [x] add the ability to run multiple iterations (e.g. `-n 10`) to `sightglass-recorder`
 - [x] fix the perf-counting in `sightglass-recorder`, probably by using [perf-event](https://crates.io/crates/perf-event) or, if not, by resolving https://github.com/gz/rust-perfcnt/issues/19
 - [x] add the ability to choose the output format (e.g. CSV vs JSON); this can probably be lifted from what sightglass currently does
 - [x] add a `sightglass-analysis` crate to aggregate and synthesize results
 - [x] add more benchmarks! (Initially, port the existing benchmarks in shootout and polybench to the new style)
 - [x] add a CLI command (`build-engine`?) for building engine libraries from `name@commit` strings in addition to passing paths to pre-built engines (the current approach)
 - [ ] eventually, integrate duplicated parts (e.g. sightglass's test runner, webui_runner's Docker infrastructure) and remove unused code
 - [x] re-enable the test (and run it in CI) verifying that `sightglass-artifact` can build Docker images into Wasm benchmarks despite differences in Docker CLI output (i.e. potentially switch to using a crate exposing the Docker API)--perhaps we should just regenerate all the benchmark Wasm files with `benchmarks-next/build.sh` and check for changes to ensure that stuff is deterministic
 - [x] add a test (and run it in CI) to run `sightglass-recorder` on a compiled Wasm benchmark--perhaps we just run all the benchmark Wasm files with `benchmarks-next/run.sh` to make sure they are all runnable

**Comment by fitzgen** [comment]
* [ ] check that a benchmark execution produced the correct result (and error otherwise, as the measurements are invalid)

**Comment by abrown** [comment]
Closing in favor of multiple issues for unfinished items.
