### ISSUE TITLE
Replace sightglass with sightglass-next

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#95]
At some point, the code in [`src`](src) will no longer be used and can be removed. When this happens, we should be able to remove that directory as well as the [`benchmarks`](benchmarks) directory (and rename `benchmarks-next` to `benchmarks`). There are several issues to close before this can happen:

 - [x] modify lucet to use new runner, #92 
 - [x] integrate the output of the new runner with the webui, #94
 - [ ] extract native baseline benchmarking from webui_runner, #96

**Comment by abrown** [comment]
This has mostly happened. Lucet is an archived project and there is a way to upload data somewhere (e.g., an ElasticSearch server). @jlb6740 had a working "run the benchmarks" natively patch somewhere; I guess we can track that in #96 and close this issue.
